### ISSUE TITLE
Gnome 44 support

### ISSUE THREAD

**Issue by spuiuk** [troyready/quarterwindows#4]
Thanks for the extension which I have been using and am very happy with. However with the latest update to Fedora 38 with Gnome 44, this extension no longer works. Can you please add support for Gnome 44 as well.

**Comment by troyready** [comment]
Sure thing @spuiuk . I meant to test it during the F38 beta but haven't yet gotten to it. I've pushed a new version listing GNOME v44 compatibility now.
