### ISSUE TITLE
New shortcuts to move window to N, S, E, or W

### ISSUE THREAD

**Issue by f-o-w-l** [troyready/quarterwindows#5]
Thanks so much for the extension! I was sorely missing a [Shiftit](https://github.com/fikovnik/ShiftIt) Linux equivalent, and this is the best program I have found.

I'm humbly requesting shortcuts to move windows to N/S/E/W, and not just the focus N/S/E/W shortcuts.

Moving a window S it fills up the bottom half of the screen, moving a window E it fills up the right half of the screen, etc.

If I have the time, I'd love to implement this myself, but I have not idea when that will be 😁 Thanks again for your work!

**Comment by troyready** [comment]
Appreciate the kind words. New version with the additional shortcuts has been submitted to the GNOME Extensions site for review.
